"""Document render engine (cp-0025) — title + sections -> a real PPTX / DOCX / PDF.

Import-guarded + stub-safe (the WORKSPACE-RULE / offline ethos):
  * the format's lib NOT installed (or OMNIVRA_DISABLE_RENDER set) -> returns a stub
    (the caller keeps a markdown deliverable).
  * installed -> a real .pptx (python-pptx) / .docx (python-docx) / .pdf (fpdf2).

Pure/sync + fast (no async needed, unlike video). Never raises: failures return
ok=False; a missing lib returns stub=True. Enable real files with:
    pip install -r requirements-docs.txt
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from app.core.logging import logger

_FMT_MODULE = {"pptx": "pptx", "docx": "docx", "pdf": "fpdf"}


def doc_available(fmt: str) -> bool:
    """True when the render lib for ``fmt`` is importable (and rendering isn't disabled)."""
    if os.environ.get("OMNIVRA_DISABLE_RENDER"):
        return False
    mod = _FMT_MODULE.get(fmt)
    if not mod:
        return False
    try:
        __import__(mod)
        return True
    except Exception:  # noqa: BLE001
        return False


def _latin1(text: str) -> str:
    """fpdf2 core fonts are latin-1; drop unencodable chars so PDF output never errors."""
    return (text or "").encode("latin-1", "replace").decode("latin-1")


def _render_pptx(title: str, sections: list[dict[str, str]], out: Path) -> None:
    from pptx import Presentation

    prs = Presentation()
    cover = prs.slides.add_slide(prs.slide_layouts[0])
    if cover.shapes.title is not None:  # defensive: a custom template may lack a title placeholder
        cover.shapes.title.text = title
    try:
        cover.placeholders[1].text = "Generated by Omnivra AI Company OS"
    except Exception:  # noqa: BLE001 - some layouts lack a subtitle placeholder
        pass
    for sec in sections:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        if slide.shapes.title is not None:
            slide.shapes.title.text = sec.get("heading", "")
        try:
            slide.placeholders[1].text_frame.text = sec.get("body", "")
        except Exception:  # noqa: BLE001
            pass
    prs.save(str(out))


def _render_docx(title: str, sections: list[dict[str, str]], out: Path) -> None:
    from docx import Document

    doc = Document()
    doc.add_heading(title, level=0)
    for sec in sections:
        doc.add_heading(sec.get("heading", ""), level=1)
        doc.add_paragraph(sec.get("body", ""))
    doc.save(str(out))


def _render_pdf(title: str, sections: list[dict[str, str]], out: Path) -> None:
    from fpdf import FPDF
    from fpdf.enums import XPos, YPos

    # A w=0 multi_cell fills to the right margin and (in fpdf2 2.7.x) leaves the X cursor
    # AT the right margin by default — so the NEXT w=0 multi_cell sees zero width and raises
    # "Not enough horizontal space". new_x=LMARGIN snaps X back to the left margin each time.
    def cell(h: float, text: str) -> None:
        pdf.multi_cell(0, h, _latin1(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 20)
    cell(10, title)
    pdf.ln(4)
    for sec in sections:
        pdf.set_font("Helvetica", "B", 14)
        cell(8, sec.get("heading", ""))
        pdf.set_font("Helvetica", "", 11)
        cell(6, sec.get("body", ""))
        pdf.ln(2)
    pdf.output(str(out))


_RENDERERS = {"pptx": _render_pptx, "docx": _render_docx, "pdf": _render_pdf}


def render_document(title: str, sections: list[dict[str, str]], output_path: Path, fmt: str) -> dict[str, Any]:
    """Render ``title`` + ``sections`` to ``output_path`` in ``fmt``. Returns {ok, stub, path?, note}."""
    if os.environ.get("OMNIVRA_DISABLE_RENDER"):
        return {"ok": True, "stub": True, "note": "render engine disabled (OMNIVRA_DISABLE_RENDER); markdown saved as the draft."}
    renderer = _RENDERERS.get(fmt)
    if renderer is None:
        return {"ok": False, "stub": False, "note": f"Unsupported format {fmt!r}."}
    try:
        __import__(_FMT_MODULE[fmt])
    except Exception as exc:  # noqa: BLE001 - lib not installed -> stub
        return {"ok": True, "stub": True, "note": f"{fmt} engine not installed ({type(exc).__name__}); markdown saved. pip install -r requirements-docs.txt"}
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        renderer(title, sections, output_path)
        return {"ok": True, "stub": False, "path": str(output_path), "note": f"Rendered {fmt}."}
    except Exception as exc:  # noqa: BLE001 - report a render failure without raising
        logger.error("Document render failed ({}): {}", fmt, repr(exc))
        return {"ok": False, "stub": False, "note": f"{fmt} render failed: {type(exc).__name__}"}
